export const GET_WALLET_BALANCE_ERROR = 'GET_WALLET_BALANCE_ERROR'
export const SAVE_WALLET_BALANCE = 'SAVE_WALLET_BALANCE'
export const GET_WALLET_ALLOWANCE_ERROR = 'GET_WALLET_ALLOWANCE_ERROR'
export const SAVE_WALLET_ALLOWANCE = 'SAVE_WALLET_ALLOWANCE'
export const SET_WALLET_ALLOWANCE_PENDING = 'SET_WALLET_ALLOWANCE_PENDING'
export const SET_WALLET_ALLOWANCE_ERROR = 'SET_WALLET_ALLOWANCE_ERROR'

export const STAKING_ERROR = 'STAKING_ERROR'
export const STAKING_PENDING = 'STAKING_PENDING'
export const STAKING_SUCCESS = 'STAKING_SUCCESS'

export const UNSTAKING_ERROR = 'UNSTAKING_ERROR'
export const UNSTAKING_PENDING = 'UNSTAKING_PENDING'
export const UNSTAKING_SUCCESS = 'UNSTAKING_SUCCESS'

export const GET_VAULT_POSITION_ERROR = 'GET_VAULT_POSITION_ERROR'
export const SAVE_VAULT_POSITION = 'SAVE_VAULT_POSITION'

export const UPDATE_TIMESTAMP = 'UPDATE_TIMESTAMP'